/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceTestRouteImport } from './routes/voice-test'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminClockRouteImport } from './routes/admin.clock'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicDebugClockRouteImport } from './routes/api/public/debug.clock'

const VoiceTestRoute = VoiceTestRouteImport.update({
  id: '/voice-test',
  path: '/voice-test',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClockRoute = AdminClockRouteImport.update({
  id: '/admin/clock',
  path: '/admin/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugClockRoute = ApiPublicDebugClockRouteImport.update({
  id: '/api/public/debug/clock',
  path: '/api/public/debug/clock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/voice-test': typeof VoiceTestRoute
  '/admin/clock': typeof AdminClockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/debug/clock': typeof ApiPublicDebugClockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/voice-test': typeof VoiceTestRoute
  '/admin/clock': typeof AdminClockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/debug/clock': typeof ApiPublicDebugClockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/voice-test': typeof VoiceTestRoute
  '/admin/clock': typeof AdminClockRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/debug/clock': typeof ApiPublicDebugClockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/voice-test'
    | '/admin/clock'
    | '/api/chat'
    | '/api/public/chat'
    | '/api/public/debug/clock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/voice-test'
    | '/admin/clock'
    | '/api/chat'
    | '/api/public/chat'
    | '/api/public/debug/clock'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/voice-test'
    | '/admin/clock'
    | '/api/chat'
    | '/api/public/chat'
    | '/api/public/debug/clock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  VoiceTestRoute: typeof VoiceTestRoute
  AdminClockRoute: typeof AdminClockRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicDebugClockRoute: typeof ApiPublicDebugClockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-test': {
      id: '/voice-test'
      path: '/voice-test'
      fullPath: '/voice-test'
      preLoaderRoute: typeof VoiceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clock': {
      id: '/admin/clock'
      path: '/admin/clock'
      fullPath: '/admin/clock'
      preLoaderRoute: typeof AdminClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug/clock': {
      id: '/api/public/debug/clock'
      path: '/api/public/debug/clock'
      fullPath: '/api/public/debug/clock'
      preLoaderRoute: typeof ApiPublicDebugClockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  VoiceTestRoute: VoiceTestRoute,
  AdminClockRoute: AdminClockRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicDebugClockRoute: ApiPublicDebugClockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
